name: Unit Testing

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  test_linux_gcc:
    strategy:
      matrix:
        compiler-version: [ 9, 10, 11, 12 ]
    runs-on: ubuntu-latest
    env:
      CC: gcc-${{ matrix.compiler-version }}
      CXX: g++-${{ matrix.compiler-version }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - run: |
          ls /usr/bin/gcc*
          ls /usr/bin/g++*
      # - run: |
      #     cmake -Bbuild \
      #       -DFirefly_ENABLE_TESTS=ON \
      #       -DFirefly_ENABLE_DOUBLE_PRECISION=ON
      #   name: Configure build directory
      # - run: |
      #     cmake --build build -j `nproc`
      #   name: Build targets
      # - run: |
      #     cmake --build build --target tests/test
      #   name: Run unit tests

  test_macos_gcc:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler-version: [ 9, 10, 11, 12 ]
    env:
      CC: gcc-${{ matrix.compiler-version }}
      CXX: g++-${{ matrix.compiler-version }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - run: brew install gcc@${{ matrix.compiler-version }}
      - run: |
          ls /usr/bin/gcc*
          ls /usr/bin/g++*

  # test_posix_clang:
  #   strategy:
  #     matrix:
  #       os: [ macos-latest, ubuntu-latest ]
  #       compiler-version: [ 11, 12, 13, 14, 15 ]
  #   runs-on: ${{ matrix.os }}
