name: Build docs

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install doxygen graphviz -y
        name: Install doxygen
      - uses: actions/checkout@v3
        name: Checkout repository
      - run: |
          doxygen
          touch docs/html/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@v4
        name: Deploy to github-pages
        with:
          folder: docs/html