name: Deploy docs

on:
  release:
    types: published
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          sudo apt install graphviz -y
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_7/doxygen-1.9.7.linux.bin.tar.gz
          tar xf doxygen-1.9.7.linux.bin.tar.gz
      - uses: actions/configure-pages@v3
      - name: build documentation
        run: |
          ./doxygen-1.9.7/bin/doxygen
          touch docs/html/.nojekyll
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "docs/html"
      - uses: actions/deploy-pages@v2
        id: deployment
